import React from "react";
import { LayoutTemplate, Sparkles, Check } from "lucide-react";
import { CanvasProject, StudioTemplate } from "./types";
import { useTranslation } from "@/contexts/LanguageContext";

interface TemplatesPanelProps {
  onLoadTemplate: (template: StudioTemplate) => void;
}

export const TEMPLATES: StudioTemplate[] = [
  {
    id: "youtube-thumbnail",
    name: "YouTube Thumbnail",
    category: "Video & Media",
    previewColor: "from-rose-900 to-slate-950",
    width: 1920,
    height: 1080,
    background: {
      type: "gradient",
      color: "#0f172a",
      gradient: {
        type: "linear",
        angle: 135,
        startColor: "#0f172a",
        endColor: "#1e1b4b",
      },
    },
    layers: [
      {
        id: "badge-top",
        type: "shape",
        name: "Category Badge",
        shapeType: "rounded-rectangle",
        x: 120,
        y: 140,
        width: 280,
        height: 64,
        rotation: 0,
        opacity: 0.95,
        isLocked: false,
        isVisible: true,
        fill: "#ef4444",
        fillType: "solid",
        strokeColor: "transparent",
        strokeWidth: 0,
        cornerRadius: 32,
      },
      {
        id: "badge-text",
        type: "text",
        name: "Badge Label",
        text: "NEW RELEASE",
        x: 120,
        y: 140,
        width: 280,
        height: 64,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 24,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.2,
        letterSpacing: 2,
      },
      {
        id: "hero-headline",
        type: "text",
        name: "Main Headline",
        text: "BUILD AMAZING\nSOFTWARE FAST",
        x: 120,
        y: 280,
        width: 1200,
        height: 280,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Impact, Charcoal, sans-serif",
        fontSize: 110,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.05,
        letterSpacing: 1,
        shadowColor: "rgba(0,0,0,0.8)",
        shadowBlur: 24,
        shadowOffsetX: 4,
        shadowOffsetY: 8,
      },
      {
        id: "sub-hook",
        type: "text",
        name: "Subtitle Hook",
        text: "Step-by-step masterclass with Oxygen Low's Software Image Studio",
        x: 120,
        y: 620,
        width: 1100,
        height: 60,
        rotation: 0,
        opacity: 0.9,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 32,
        fontWeight: "normal",
        fontStyle: "normal",
        underline: false,
        color: "#38bdf8",
        textAlign: "left",
        lineHeight: 1.2,
        letterSpacing: 0,
      },
    ],
  },
  {
    id: "sale-promo",
    name: "Special Offer / Sale",
    category: "Marketing",
    previewColor: "from-amber-700 to-rose-950",
    width: 1080,
    height: 1080,
    background: {
      type: "gradient",
      color: "#0f172a",
      gradient: {
        type: "linear",
        angle: 135,
        startColor: "#18181b",
        endColor: "#27272a",
      },
    },
    layers: [
      {
        id: "card-backdrop",
        type: "shape",
        name: "Card Container",
        shapeType: "rounded-rectangle",
        x: 80,
        y: 80,
        width: 920,
        height: 920,
        rotation: 0,
        opacity: 0.7,
        isLocked: false,
        isVisible: true,
        fill: "#18181b",
        fillType: "gradient",
        gradientStart: "#1f2937",
        gradientEnd: "#111827",
        gradientAngle: 180,
        strokeColor: "#374151",
        strokeWidth: 2,
        cornerRadius: 36,
      },
      {
        id: "tag-pill",
        type: "shape",
        name: "Tag Pill",
        shapeType: "rounded-rectangle",
        x: 390,
        y: 180,
        width: 300,
        height: 56,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fill: "#f59e0b",
        fillType: "solid",
        strokeColor: "transparent",
        strokeWidth: 0,
        cornerRadius: 28,
      },
      {
        id: "tag-text",
        type: "text",
        name: "Tag Text",
        text: "LIMITED TIME OFFER",
        x: 390,
        y: 180,
        width: 300,
        height: 56,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 18,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#000000",
        textAlign: "center",
        lineHeight: 1.2,
        letterSpacing: 1.5,
      },
      {
        id: "big-discount",
        type: "text",
        name: "Big Discount",
        text: "50% OFF",
        x: 140,
        y: 310,
        width: 800,
        height: 180,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Impact, Charcoal, sans-serif",
        fontSize: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#f59e0b",
        textAlign: "center",
        lineHeight: 1,
        letterSpacing: 0,
        shadowColor: "rgba(245,158,11,0.4)",
        shadowBlur: 30,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        id: "promo-desc",
        type: "text",
        name: "Promo Description",
        text: "Upgrade your productivity suite today.\nAvailable for all accounts.",
        x: 190,
        y: 540,
        width: 700,
        height: 100,
        rotation: 0,
        opacity: 0.9,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 28,
        fontWeight: "normal",
        fontStyle: "normal",
        underline: false,
        color: "#f3f4f6",
        textAlign: "center",
        lineHeight: 1.4,
        letterSpacing: 0,
      },
      {
        id: "cta-btn",
        type: "shape",
        name: "CTA Button",
        shapeType: "rounded-rectangle",
        x: 365,
        y: 740,
        width: 350,
        height: 80,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fill: "#f59e0b",
        fillType: "gradient",
        gradientStart: "#f59e0b",
        gradientEnd: "#d97706",
        gradientAngle: 90,
        strokeColor: "transparent",
        strokeWidth: 0,
        cornerRadius: 40,
      },
      {
        id: "cta-text",
        type: "text",
        name: "CTA Label",
        text: "GET STARTED NOW",
        x: 365,
        y: 740,
        width: 350,
        height: 80,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 22,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#000000",
        textAlign: "center",
        lineHeight: 1.2,
        letterSpacing: 1,
      },
    ],
  },
  {
    id: "minimalist-quote",
    name: "Inspirational Quote",
    category: "Social Media",
    previewColor: "from-slate-800 to-indigo-950",
    width: 1080,
    height: 1080,
    background: {
      type: "color",
      color: "#090d16",
      gradient: {
        type: "linear",
        angle: 135,
        startColor: "#090d16",
        endColor: "#111827",
      },
    },
    layers: [
      {
        id: "quote-mark",
        type: "text",
        name: "Quote Symbol",
        text: "“",
        x: 140,
        y: 200,
        width: 200,
        height: 160,
        rotation: 0,
        opacity: 0.35,
        isLocked: false,
        isVisible: true,
        fontFamily: "Georgia, serif",
        fontSize: 180,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#6366f1",
        textAlign: "left",
        lineHeight: 1,
        letterSpacing: 0,
      },
      {
        id: "quote-content",
        type: "text",
        name: "Quote Body",
        text: "Simplicity is the soul of efficiency.",
        x: 140,
        y: 380,
        width: 800,
        height: 200,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Georgia, serif",
        fontSize: 54,
        fontWeight: "normal",
        fontStyle: "italic",
        underline: false,
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.3,
        letterSpacing: 0,
      },
      {
        id: "quote-divider",
        type: "shape",
        name: "Divider Line",
        shapeType: "line",
        x: 140,
        y: 620,
        width: 120,
        height: 4,
        rotation: 0,
        opacity: 0.8,
        isLocked: false,
        isVisible: true,
        fill: "#6366f1",
        fillType: "solid",
        strokeColor: "#6366f1",
        strokeWidth: 4,
        cornerRadius: 2,
      },
      {
        id: "quote-author",
        type: "text",
        name: "Author",
        text: "Austin Freeman",
        x: 140,
        y: 660,
        width: 800,
        height: 50,
        rotation: 0,
        opacity: 0.7,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 24,
        fontWeight: "600",
        fontStyle: "normal",
        underline: false,
        color: "#a5b4fc",
        textAlign: "left",
        lineHeight: 1.2,
        letterSpacing: 2,
      },
    ],
  },
  {
    id: "social-banner",
    name: "Social Header Banner",
    category: "Banners & Headers",
    previewColor: "from-cyan-900 to-blue-950",
    width: 1200,
    height: 630,
    background: {
      type: "gradient",
      color: "#080c14",
      gradient: {
        type: "linear",
        angle: 120,
        startColor: "#022c22",
        endColor: "#082f49",
      },
    },
    layers: [
      {
        id: "banner-accent-badge",
        type: "shape",
        name: "Tech Ribbon",
        shapeType: "badge",
        x: 960,
        y: 120,
        width: 160,
        height: 160,
        rotation: 12,
        opacity: 0.85,
        isLocked: false,
        isVisible: true,
        fill: "#06b6d4",
        fillType: "gradient",
        gradientStart: "#10b981",
        gradientEnd: "#06b6d4",
        gradientAngle: 45,
        strokeColor: "transparent",
        strokeWidth: 0,
      },
      {
        id: "banner-title",
        type: "text",
        name: "Banner Title",
        text: "OXYGEN LOW'S SOFTWARE",
        x: 80,
        y: 180,
        width: 840,
        height: 80,
        rotation: 0,
        opacity: 1,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 48,
        fontWeight: "bold",
        fontStyle: "normal",
        underline: false,
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.1,
        letterSpacing: 1,
      },
      {
        id: "banner-desc",
        type: "text",
        name: "Banner Tagline",
        text: "The all-in-one suite of modern web applications, AI tools & creative studios.",
        x: 80,
        y: 280,
        width: 800,
        height: 80,
        rotation: 0,
        opacity: 0.85,
        isLocked: false,
        isVisible: true,
        fontFamily: "Inter, sans-serif",
        fontSize: 24,
        fontWeight: "normal",
        fontStyle: "normal",
        underline: false,
        color: "#a7f3d0",
        textAlign: "left",
        lineHeight: 1.3,
        letterSpacing: 0,
      },
    ],
  },
];

export const TemplatesPanel: React.FC<TemplatesPanelProps> = ({
  onLoadTemplate,
}) => {
  const { t } = useTranslation();

  return (
    <div className="space-y-4 p-3">
      <div className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground flex items-center justify-between">
        <span>{t("imageStudio.templates", undefined, "Design Templates")}</span>
        <span className="text-[10px] font-mono">{TEMPLATES.length}</span>
      </div>

      <p className="text-xs text-muted-foreground">
        {t(
          "imageStudio.templatesDesc",
          undefined,
          "Select a starter layout to quickly jumpstart your graphics project.",
        )}
      </p>

      <div className="space-y-2.5">
        {TEMPLATES.map((tmpl) => (
          <div
            key={tmpl.id}
            onClick={() => onLoadTemplate(tmpl)}
            className="p-3 rounded-xl border border-border bg-card/60 hover:bg-accent transition-all cursor-pointer group hover:scale-[1.01] hover:border-primary/50 relative overflow-hidden"
          >
            {/* Visual gradient preview pill */}
            <div
              className={`h-16 w-full rounded-lg bg-gradient-to-r ${tmpl.previewColor} mb-2.5 flex items-center justify-between px-3 border border-white/10`}
            >
              <div className="flex items-center gap-2 text-white font-bold text-xs drop-shadow">
                <Sparkles className="w-4 h-4 text-primary" />
                <span>{tmpl.name}</span>
              </div>
              <span className="text-[10px] font-mono text-white/80 bg-black/40 px-1.5 py-0.5 rounded">
                {tmpl.width}×{tmpl.height}
              </span>
            </div>

            <div className="flex items-center justify-between text-xs">
              <span className="text-muted-foreground text-[11px]">
                {tmpl.category}
              </span>
              <span className="text-primary font-medium text-[11px] group-hover:underline flex items-center gap-1">
                {t("imageStudio.useTemplate", undefined, "Use Template")}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
