onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
overrides:
  music-metadata@<=11.12.3: 11.12.3
  file-type@16.5.4: https://npm.aikido.io/11e3e0ee71cce3f978d5a/file-type@16.5.4-aikido.1
  dompurify@<=3.4.11: 3.4.11
  inline-style-parser@<=0.2.9: 0.2.9
